package com.eneve.agent.planner;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import com.anthropic.client.AnthropicClient;
import com.anthropic.models.messages.ContentBlock;
import com.anthropic.models.messages.Message;
import com.anthropic.models.messages.MessageCreateParams;
import com.anthropic.models.messages.MessageParam;
import com.anthropic.models.messages.Model;
import com.anthropic.models.messages.Usage;
import com.eneve.agent.agent.AiCallRecord;
import com.eneve.agent.agent.AiCallStore;
import com.eneve.agent.agent.PromptTemplateService;
import com.eneve.agent.util.UrlUtils;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

/**
 * Generates an AI-powered execution plan from a specification.
 * Uses a single Claude call (no tool-use loop) to decompose a spec into
 * ordered phases and steps that can be submitted to the job queue.
 * Follows the same single-call pattern as PrSummaryGenerator.
 */
@ApplicationScoped
public class PlannerService {

    private static final Logger LOG = Logger.getLogger(PlannerService.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    @ConfigProperty(name = "anthropic.model", defaultValue = "claude-sonnet-4-20250514")
    String modelName;

    @ConfigProperty(name = "planner.max-tokens", defaultValue = "8192")
    long maxTokens;

    @Inject
    AnthropicClient client;

    @Inject
    AiCallStore aiCallStore;

    @Inject
    PromptTemplateService promptTemplates;

    /**
     * Generate an execution plan from a specification text.
     *
     * @param specText     the full specification (Jira ticket text, free text, etc.)
     * @param repoUrl      the target repository URL
     * @param targetBranch the base branch (e.g. "main")
     * @param sourceType   JIRA, FREE_TEXT, or URL
     * @param sourceRef    JIRA key, URL, or null
     * @return a DRAFT ExecutionPlan with phases and steps, or null on failure
     */
    public ExecutionPlan generatePlan(String specText, String repoUrl,
                                      String targetBranch, String sourceType, String sourceRef) {
        if (specText == null || specText.isBlank()) {
            LOG.warn("PlannerService: empty spec text, cannot generate plan");
            return null;
        }

        String prompt = buildPrompt(specText, repoUrl, targetBranch);
        String planId = "plan-" + UUID.randomUUID();

        String responseText = callClaude(prompt, planId);
        if (responseText == null) {
            return null;
        }

        PlanData planData = parsePlanData(responseText, planId);
        if (planData == null) {
            return null;
        }

        String title = deriveTitle(specText, sourceRef);
        Instant now = Instant.now();

        return new ExecutionPlan(
                planId,
                PlanStatus.DRAFT.name(),
                sourceType != null ? sourceType : "FREE_TEXT",
                sourceRef,
                repoUrl,
                targetBranch != null ? targetBranch : "main",
                title,
                planData,
                now,
                now,
                null,
                null,
                null
        );
    }

    private String buildPrompt(String specText, String repoUrl, String targetBranch) {
        // Strip credentials so they are never embedded in the AI prompt or in
        // plan steps generated by the model.
        String safeRepoUrl = UrlUtils.stripCredentials(repoUrl);
        return promptTemplates.resolve("planner", Map.of(
                "REPO_URL", safeRepoUrl != null ? safeRepoUrl : "(unspecified)",
                "TARGET_BRANCH", targetBranch != null ? targetBranch : "main",
                "SPEC", specText
        ));
    }

    private String callClaude(String prompt, String planId) {
        MessageCreateParams params = MessageCreateParams.builder()
                .model(Model.of(modelName))
                .maxTokens(maxTokens)
                .messages(List.of(
                        MessageParam.builder()
                                .role(MessageParam.Role.USER)
                                .content(prompt)
                                .build()
                ))
                .build();

        long startNs = System.nanoTime();
        Message response;
        try {
            response = client.messages().create(params);
        } catch (Exception e) {
            long durationMs = (System.nanoTime() - startNs) / 1_000_000;
            aiCallStore.save(new AiCallRecord(
                    null, planId, "PLAN", modelName, null,
                    0, 0, 0, 0,
                    null, null, durationMs,
                    true, e.getMessage(), Instant.now()));
            LOG.errorf("PlannerService Claude call failed: %s", e.getMessage());
            return null;
        }
        long durationMs = (System.nanoTime() - startNs) / 1_000_000;

        Usage usage = response.usage();
        String stopReason = response.stopReason().map(Object::toString).orElse(null);
        aiCallStore.save(new AiCallRecord(
                null, planId, "PLAN", modelName, null,
                usage.inputTokens(), usage.outputTokens(),
                usage.cacheCreationInputTokens().orElse(0L),
                usage.cacheReadInputTokens().orElse(0L),
                stopReason, null, durationMs,
                false, null, Instant.now()));

        LOG.infof("Plan generated — tokens: in=%d, out=%d, duration=%dms",
                usage.inputTokens(), usage.outputTokens(), durationMs);

        for (ContentBlock block : response.content()) {
            if (block.isText()) {
                return block.asText().text().trim();
            }
        }
        return null;
    }

    private PlanData parsePlanData(String responseText, String planId) {
        String cleaned = responseText.strip();
        if (cleaned.startsWith("```")) {
            int firstNewline = cleaned.indexOf('\n');
            int lastFence = cleaned.lastIndexOf("```");
            if (firstNewline > 0 && lastFence > firstNewline) {
                cleaned = cleaned.substring(firstNewline + 1, lastFence).strip();
            }
        }

        try {
            JsonNode root = MAPPER.readTree(cleaned);
            JsonNode phasesNode = root.path("phases");
            if (!phasesNode.isArray()) {
                LOG.warnf("PlannerService: response missing 'phases' array for plan %s", planId);
                return null;
            }

            var phases = new java.util.ArrayList<PlanPhase>();
            for (JsonNode phaseNode : phasesNode) {
                int order = phaseNode.path("order").asInt(phases.size() + 1);
                String name = phaseNode.path("name").asText("Phase " + order);
                boolean gate = phaseNode.path("gateOnSuccess").asBoolean(true);

                var steps = new java.util.ArrayList<PlanStep>();
                for (JsonNode stepNode : phaseNode.path("steps")) {
                    Map<String, String> stepParams = new java.util.LinkedHashMap<>();
                    JsonNode paramsNode = stepNode.path("params");
                    if (paramsNode.isObject()) {
                        paramsNode.fields().forEachRemaining(entry ->
                                stepParams.put(entry.getKey(), entry.getValue().asText("")));
                    }

                    String jobIdValue = stepNode.path("jobId").isNull() ? null : stepNode.path("jobId").asText(null);

                    steps.add(new PlanStep(
                            stepNode.path("stepId").asText("step-" + (steps.size() + 1)),
                            stepNode.path("jobType").asText("FIX"),
                            stepNode.path("title").asText(""),
                            stepNode.path("prompt").asText(""),
                            stepNode.path("status").asText("PENDING"),
                            jobIdValue,
                            stepParams
                    ));
                }
                phases.add(new PlanPhase(order, name, gate, steps));
            }

            LOG.infof("PlannerService: parsed plan with %d phases for %s", phases.size(), planId);
            return new PlanData(phases);

        } catch (Exception e) {
            LOG.errorf("PlannerService: failed to parse plan JSON for %s: %s", planId, e.getMessage());
            return null;
        }
    }

    private String deriveTitle(String specText, String sourceRef) {
        if (sourceRef != null && !sourceRef.isBlank()) {
            return sourceRef;
        }
        String firstLine = specText.lines().findFirst().orElse("").strip();
        return firstLine.length() > 80 ? firstLine.substring(0, 77) + "..." : firstLine;
    }
}
