#!/usr/bin/env bash
# =============================================================================
# aiw-fetch-secrets.sh
# =============================================================================
# Pulls all AIW Code Agent secrets from Bitwarden (vault.sunstein.cloud) via
# the production VPS, and writes a complete .env file to stdout.
#
# Usage:
#   ./scripts/aiw-fetch-secrets.sh > .env
#   ./scripts/aiw-fetch-secrets.sh --frontend > ../code-agent-ui/.env.local
#
# Requirements:
#   - SSH access to root@72.61.44.159 (the VPS where bw + vaultwarden live)
#   - The vault must be unlocked on the VPS:
#       ssh root@72.61.44.159 'bw login --apikey || bw unlock'
#       export BW_SESSION="<the session token it prints>"
#   - Or, if you keep BW_SESSION in your local env, it will be forwarded.
#
# This script does NOT store any secret on the local disk except in the file
# you redirect to. Do not commit that file (.env / .env.local are gitignored).
# =============================================================================

set -euo pipefail

VPS="${AIW_VPS:-root@72.61.44.159}"
LITELLM_URL="${LITELLM_GATEWAY_URL:-http://72.61.44.159:4000}"
MODE="backend"
[[ "${1:-}" == "--frontend" ]] && MODE="frontend"

# -----------------------------------------------------------------------------
# Helper: fetch one bw item field via SSH to the VPS
# -----------------------------------------------------------------------------
bw_get() {
  local item="$1"
  local field="${2:-password}"
  ssh -o BatchMode=yes -o ConnectTimeout=5 "$VPS" \
    "BW_SESSION='${BW_SESSION:-}' bw --nointeraction --raw get item '$item' 2>/dev/null \
       | jq -r '.login.${field} // .fields[]? | select(.name==\"${field}\") | .value' 2>/dev/null \
       || echo ''"
}

# -----------------------------------------------------------------------------
# Sanity check: vault unlocked?
# -----------------------------------------------------------------------------
status=$(ssh -o BatchMode=yes -o ConnectTimeout=5 "$VPS" \
  "BW_SESSION='${BW_SESSION:-}' bw status 2>/dev/null | jq -r .status" || echo "unreachable")
if [[ "$status" != "unlocked" ]]; then
  echo "ERROR: Bitwarden on $VPS is '$status' (need 'unlocked')." >&2
  echo "Run on the VPS:" >&2
  echo "  ssh $VPS" >&2
  echo "  bw unlock --raw   # copy the BW_SESSION it prints" >&2
  echo "  export BW_SESSION='<paste>'" >&2
  echo "Then re-run this script with BW_SESSION set in your local env." >&2
  exit 1
fi

# -----------------------------------------------------------------------------
# Sanity check: LiteLLM reachable?
# -----------------------------------------------------------------------------
LITELLM_KEY=$(bw_get litellm-master-key)
if ! curl -sS --max-time 5 -H "Authorization: Bearer $LITELLM_KEY" \
     "$LITELLM_URL/v1/models" >/dev/null; then
  echo "WARNING: LiteLLM at $LITELLM_URL not reachable. Continuing anyway." >&2
fi

# -----------------------------------------------------------------------------
# Emit .env contents
# -----------------------------------------------------------------------------
emit_backend() {
cat <<EOF
# Generated by aiw-fetch-secrets.sh on $(date -Iseconds)
# DO NOT COMMIT THIS FILE.

# --- LLM via LiteLLM gateway ---
LITELLM_GATEWAY_URL=$LITELLM_URL
LITELLM_MASTER_KEY=$LITELLM_KEY
LITELLM_ROUTING_PRIMARY=primary
LITELLM_ROUTING_FAST=fast
LITELLM_ROUTING_PLANNING=fast
LITELLM_ROUTING_REASONING=reasoning

# --- GitHub ---
GIT_PLATFORM=github
GITHUB_TOKEN=$(bw_get github-aiw-code-agent-pat)
GITHUB_AGENT_USER=aiw-code-agent
GIT_AUTHOR_NAME=aiw-code-agent
GIT_AUTHOR_EMAIL=code-agent@aiwhisperers.io
WEBHOOK_SECRET_GITHUB=$(bw_get github-webhook-secret)

# --- Linear ---
LINEAR_API_KEY=$(bw_get linear-api-key)
LINEAR_TEAM_ID=$(bw_get linear-api-key team_id)
LINEAR_AGENT_LABEL=aiw-agent

# --- Supabase ---
SUPABASE_URL=$(bw_get supabase-codeagent url)
SUPABASE_ANON_KEY=$(bw_get supabase-codeagent anon_key)
SUPABASE_SERVICE_KEY=$(bw_get supabase-codeagent service_key)
DATABASE_URL=$(bw_get supabase-codeagent pg_url)
DATABASE_USER=postgres
DATABASE_PASSWORD=$(bw_get supabase-codeagent pg_password)

# --- Hermes notifications ---
HERMES_GATEWAY_URL=http://72.61.44.159:8765
HERMES_DEFAULT_TARGET=telegram

# --- Embeddings ---
VOYAGE_API_KEY=$(bw_get voyage-api-key)
OPENAI_API_KEY=$(bw_get openai-api-key)
OLLAMA_BASE_URL=http://100.110.9.12:11434

# --- Misc ---
TAVILY_API_KEY=$(bw_get tavily-api-key)
API_KEY=$(bw_get code-agent-api-key)
CORS_ALLOWED_ORIGINS=http://localhost:5173,https://code-agent.aiwhisperers.io
EOF
}

emit_frontend() {
cat <<EOF
# Generated by aiw-fetch-secrets.sh --frontend on $(date -Iseconds)
# DO NOT COMMIT THIS FILE.

VITE_API_URL=http://localhost:8080/api
VITE_GIT_PLATFORM=github
VITE_GITHUB_URL=https://github.com

# Supabase Auth (replaces Keycloak)
VITE_SUPABASE_URL=$(bw_get supabase-codeagent url)
VITE_SUPABASE_ANON_KEY=$(bw_get supabase-codeagent anon_key)
EOF
}

if [[ "$MODE" == "frontend" ]]; then
  emit_frontend
else
  emit_backend
fi
